typedef enum
  {
    CMI_STATUS_CREATED,
    CMI_STATUS_INITIALIZING,
    CMI_STATUS_INITIALIZED,
    CMI_STATUS_UPDATING,
    CMI_STATUS_UPDATED,
    CMI_STATUS_FINALIZING,
    CMI_STATUS_FINALIZED
  }
  CMI_Component_status;
