version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

formats:
  - htmlzip

python:
  install:
    - requirements: docs/source/requirements.txt
    - method: pip
      path: .
  system_packages: false
