name: Documentation

on:
    push:
        paths:
            - "docs/**"
            - "AUTHORS.rst"
            - "CITATION.rst"
            - "CODE-OF-CONDUCT.rst"
            - "CONTRIBUTING.rst"
            - "README.rst"
    pull_request:
        paths:
            - "docs/**"
            - "AUTHORS.rst"
            - "CITATION.rst"
            - "CODE-OF-CONDUCT.rst"
            - "CONTRIBUTING.rst"
            - "README.rst"

jobs:
    build:
        # We want to run on external PRs, but not on our own internal PRs as they'll be run
        # by the push to the branch. Without this if check, checks are duplicated since
        # internal PRs match both the push and pull_request events.
        if:
          github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
          github.repository
    
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-python@v2

          - name: Install dependencies
            run: pip install sphinx

          - name: Build documentation
            run: make -C docs clean html
